<?php

namespace App\Services;

use App\Enums\EmailTemplateSlot;
use App\Enums\JobStatus;
use App\Enums\TechnicianJobStatus;
use App\Jobs\WriteAuditLog;
use App\Mail\EmailTemplateMail;
use App\Mail\JobInvitationMail;
use App\Models\EmailTemplate;
use App\Models\ServiceJob;
use App\Models\TechnicianProfile;
use App\Models\User;
use App\Services\Emails\EmailTemplateRenderer;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

/**
 * Manages the full invitation lifecycle for a (job, technician) pair (US-09.2/09.4).
 *
 * Responsibilities:
 *   - Generate a unique, expiring invitation token stored in job_technicians.
 *   - Dispatch a queued invitation email to the technician.
 *   - Invalidate the previous token on resend so only one live link exists.
 *   - Audit every send/resend event.
 *
 * The signed URL (used as the actual link in the email) is generated by TechnicianUrlService
 * and embeds both job_id and technician_profile_id for server-side scope validation.
 */
class JobInvitationService
{
    /** Invitation link TTL in hours (§14.3). */
    public const TTL_HOURS = 72;

    public function __construct(
        private readonly TechnicianUrlService $urlService,
        private readonly EmailTemplateRenderer $renderer,
    ) {}

    /**
     * Send (or resend) an invitation to one technician for a job.
     *
     * If the technician is already in the pivot (re-invite scenario), the old token
     * is invalidated and a fresh one is issued; lifecycle state is preserved.
     *
     * @throws \RuntimeException if the profile is not assigned to this job
     */
    public function invite(ServiceJob $job, TechnicianProfile $profile, User $invitedBy): void
    {
        $token     = Str::random(48);
        $expiresAt = now()->addHours(self::TTL_HOURS);

        DB::transaction(function () use ($job, $profile, $token, $expiresAt): void {
            $existing = DB::table('job_technicians')
                ->where('job_id', $job->id)
                ->where('technician_profile_id', $profile->id)
                ->first();

            if ($existing) {
                // Resend — invalidate old token, preserve lifecycle state
                DB::table('job_technicians')
                    ->where('job_id', $job->id)
                    ->where('technician_profile_id', $profile->id)
                    ->update([
                        'invitation_token' => $token,
                        'token_expires_at' => $expiresAt,
                    ]);
            } else {
                // First invite — create pivot row
                DB::table('job_technicians')->insert([
                    'job_id'                => $job->id,
                    'technician_profile_id' => $profile->id,
                    'technician_status'     => TechnicianJobStatus::Invited->value,
                    'invitation_token'      => $token,
                    'token_expires_at'      => $expiresAt,
                ]);
            }
        });

        // Update job status to Invited if still Draft (Draft → Invited)
        if ($job->job_status->value === 'draft') {
            try {
                $job->transitionTo(JobStatus::Invited, $invitedBy);
            } catch (\InvalidArgumentException) {
                // Job already past Draft — transition not required
            }
        }

        // Generate the signed URL (embeds profile_id + token for validation)
        $signedUrl = $this->urlService->generateForProfile($job->id, $profile->id, $token, self::TTL_HOURS);

        // Dispatch queued email — default path unless a PM has customised this slot (US-16.2)
        $this->sendInvitationEmail($job, $profile, $signedUrl);

        WriteAuditLog::dispatch(
            userId: $invitedBy->id,
            userRole: $invitedBy->role->value,
            action: 'job.invitation_sent',
            auditableType: 'App\\Models\\ServiceJob',
            auditableId: $job->id,
            before: null,
            after: ['technician_profile_id' => $profile->id, 'email' => $profile->email],
            ipAddress: request()->ip(),
            userAgent: request()->userAgent(),
        );
    }

    /**
     * Send the default JobInvitationMail unless a PM has saved a custom template for the
     * JobInvitation slot (US-16.2) — the default path is unchanged from before US-16.2 existed.
     */
    private function sendInvitationEmail(ServiceJob $job, TechnicianProfile $profile, string $signedUrl): void
    {
        $hasCustomTemplate = EmailTemplate::where('slot', EmailTemplateSlot::JobInvitation->value)
            ->whereNotNull('subject')
            ->exists();

        if (! $hasCustomTemplate) {
            Mail::to($profile->email)->queue(new JobInvitationMail($job, $profile, $signedUrl));

            return;
        }

        $rendered = $this->renderer->render(
            EmailTemplateSlot::JobInvitation,
            $this->invitationVariables($job->loadMissing('store'), $profile, $signedUrl),
        );

        Mail::to($profile->email)->queue(new EmailTemplateMail(
            subjectLine: $rendered['subject'],
            renderedBody: $rendered['body'],
            ctaUrl: $signedUrl,
            ctaLabel: 'View job & respond',
        ));
    }

    /** @return array<string, string> */
    private function invitationVariables(ServiceJob $job, TechnicianProfile $profile, string $signedUrl): array
    {
        $scheduledDate = '';

        if ($job->scheduled_date) {
            $dt = Carbon::parse(
                $job->scheduled_date->format('Y-m-d').($job->scheduled_time ? ' '.$job->scheduled_time : ''),
                'UTC',
            )->setTimezone($job->job_timezone);

            $scheduledDate = $dt->format('l, d F Y');

            if ($job->scheduled_time) {
                $scheduledDate .= ' at '.$dt->format('g:i A').' ('.$job->job_timezone.')';
            }
        }

        return [
            'technician_name' => $profile->name,
            'job_reference'   => $job->job_reference,
            'job_name'        => $job->job_name,
            // store_id is a NOT NULL FK (§3.2) — every job has exactly one store.
            'store_name'     => $job->store->store_name,
            'store_address'  => trim($job->store->address_line1.', '.$job->store->suburb.' '.$job->store->state->value),
            'scheduled_date' => $scheduledDate,
            'signed_url'     => $signedUrl,
        ];
    }

    /**
     * Verify that a request's token matches the stored token for a (job, profile) pair
     * and that the token has not expired.
     *
     * Returns the technician_profile_id if valid, null otherwise.
     */
    public function resolveToken(int $jobId, string $token): ?int
    {
        $row = DB::table('job_technicians')
            ->where('job_id', $jobId)
            ->where('invitation_token', $token)
            ->where('token_expires_at', '>', now())
            ->first();

        return $row ? (int) $row->technician_profile_id : null;
    }
}
